name: Build and Push Docker Image to Azure Container Registry

on:
  pull_request:
    types: [closed]
    branches:
      - master
  workflow_dispatch:

env:
  project_name: devanand

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout Repository
        uses : actions/checkout@v4

      - name : Calculate New Tag
        run: |
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            PREFIX="Prod_"
            tag_version=1.00
            echo "Inside Prod"
            echo "The reference is ${{ github.ref }}"
          elif [ "${{ github.ref }}" = "refs/heads/dev" ]; then
            PREFIX="Dev_"
            tag_version=1.00
            echo "Inside Dev"
            echo "The reference is ${{ github.ref }}"
          fi

          # Get the latest tag
          LATEST_TAG=$(git tag -l "${PREFIX}*" | sort -V | tail -n 1)

          if [ -z "$LATEST_TAG" ]; then
            # NEW_TAG="${PREFIX}$tag_version"
            NEW_TAG=$tag_version
          else
            NUMERIC_PART=$(echo "$LATEST_TAG" | sed "s/${PREFIX}//")
            IFS='.' read -r INTEGER FRACTION <<< "$NUMERIC_PART"
            NEW_FRAC=$(printf "%02d" $((10#$FRACTION + 1)))
            NEW_TAG="${INTEGER}.${NEW_FRAC}"
          fi

          echo "NEW_TAG=${NEW_TAG}" >> $GITHUB_ENV
          echo "Next tag will be: $NEW_TAG"

      - name : Get ACR Credentials
        run: |
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            echo "ACR_USERNAME="testp${{env.project_name}}" >> $GITHUB_ENV
            echo "ACR_PASSWORD=${{secrets.PRD_ACR_PASSWORD}} >> $GITHUB_ENV
            echo "Inside Prod"
            echo "Pushing to ACR Repo, $ACR_USERNAME"
          elif [ "${{ github.ref }}" = "refs/heads/dev" ]; then
            echo "ACR_USERNAME=testn${{env.project_name}}">> $GITHUB_ENV
            echo "ACR_PASSWORD=${{secrets.NPRD_ACR_PASSWORD}}" >> $GITHUB_ENV
            echo "Inside Dev"
            echo "Pushing to ACR Repo, $ACR_USERNAME"
            echo "ACR Password, $ACR_PASSWORD"
          fi

      - name : Login to ACR
        uses: azure/docker-login@v2
        with:
          login-server: $ACR_USERNAME.azurecr.io
          username: $ACR_USERNAME
          password: $ACR_PASSWORD

      # - name : Push Image to ACR
      #   run: |
      #     docker build . -t $ACR_USERNAME.azurecr.io/$ACR_USERNAME:v$NEW_TAG
      #     docker push $ACR_USERNAME.azurecr.io/$ACR_USERNAME:v$NEW_TAG

      - name: Build and push container image to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{env.ACR_USERNAME}}.azurecr.io/${{env.ACR_USERNAME}}:v${{env.NEW_TAG}}