name: Build and Push Docker Image to Development Azure Container Registry

on:
  push:
    branches:
      - dev  # Change this to your branch name if different

env:
  IMAGE_NAME: testdevanand

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{secrets.ACR_LOGIN_SERVER}}
        username: ${{secrets.ACR_USERNAME}}
        password: ${{secrets.ACR_PASSWORD}}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{secrets.ACR_LOGIN_SERVER}}/${{env.IMAGE_NAME}}:latest

  create-tag:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Git
        run: |
          git config user.email "admin@gmail.com"
          git config user.name "Admin"
        
      - name: create the tag
        run: |
          build_version=${{ github.run_number }}
          tag_version_prefix=1.000
          padded_build_version="0."
          padded_build_version+=$(printf '%03d' $build_version)
          final_tag_version=$(echo "$tag_version_prefix + $padded_build_version" | bc)
          git tag -a "Prod_Tag_$final_tag_version" -m "Version $build_version"
          git push --follow-tags
